[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.22" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@gnosis.pm/=node_modules/@gnosis.pm/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]
optimizer = true
optimizer_runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
