/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPlantoidSpawnerInterface extends ethers.utils.Interface {
  functions: {
    "spawnPlantoid(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "spawnPlantoid",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "spawnPlantoid",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPlantoidSpawner extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPlantoidSpawnerInterface;

  functions: {
    spawnPlantoid(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "spawnPlantoid(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  spawnPlantoid(
    arg0: string,
    arg1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "spawnPlantoid(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    spawnPlantoid(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "spawnPlantoid(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    spawnPlantoid(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "spawnPlantoid(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    spawnPlantoid(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "spawnPlantoid(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
