/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPlantoidSpawner } from "./IPlantoidSpawner";

export class IPlantoidSpawnerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlantoidSpawner {
    return new Contract(address, _abi, signerOrProvider) as IPlantoidSpawner;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "spawnPlantoid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
