/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRemixNft } from "./IRemixNft";

export class IRemixNftFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRemixNft {
    return new Contract(address, _abi, signerOrProvider) as IRemixNft;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "licenseHolder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
