/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRemixNftInterface extends ethers.utils.Interface {
  functions: {
    "licenseHolder(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "licenseHolder",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "licenseHolder",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRemixNft extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRemixNftInterface;

  functions: {
    licenseHolder(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "licenseHolder(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;
  };

  licenseHolder(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "licenseHolder(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    licenseHolder(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "licenseHolder(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    licenseHolder(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "licenseHolder(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    licenseHolder(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "licenseHolder(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
